### ISSUE TITLE
Getting error in executing the Isolated_Speech_Recognition.py

### ISSUE THREAD

**Issue by hkroclee** [prakashpandey9/IsolatedSpeechRecognition#4]
in Isolated_Speech_Recognition.py, StratifiedShuffleSplit was imported from sklearn.cross_validation, I just make changes and import StratifiedShuffleSplit from sklearn.model_selection, to remove DeprecationWarning,

now I got the error:
Traceback (most recent call last):
  File "Isolated_Speech_Recognition.py", line 269, in <module>
    _ = [model.train(X_train[y_train == y, :, :]) for m, y in zip(ms, ys)]
  File "Isolated_Speech_Recognition.py", line 269, in <listcomp>
    _ = [model.train(X_train[y_train == y, :, :]) for m, y in zip(ms, ys)]
NameError: name 'model' is not defined

**Comment by bhaskarkvvsr** [comment]
you need to use the variable m instead of the model there
